# This file describes an application. You can have multiple applications
# in the same project.


# Redis configuration
stage:
  deploy:
    REDIS_USE_SLAVE_CONNECTION: true
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
    MYSQL_USE_SLAVE_CONNECTION: true
    CLEAN_STATIC_FILES: true
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 20000
      consumers:
        - product_action_attribute.update
        - product_action_attribute.website.update
        - media.storage.catalog.image.resize
        - codegeneratorProcessor
        - exportProcessor
        - quoteItemCleaner
        - inventoryQtyCounter
        - media.content.synchronization
        - media.gallery.synchronization
        - async.operations.all
  build:
    QUALITY_PATCHES:
      - ACSD-47332
