# This file describes an application. You can have multiple applications
# in the same project.
# The name of this app. Must be unique within a project.
name: mymagento

# The toolstack used to build the application.
type: php:8.1
build:
  flavor: none
  # 2. Add composer ^2.0 as a php dependency.
dependencies:
  php:
    composer/composer: '2.2.4'
# Enable extensions required by Magento 2
runtime:
  extensions:
    - xsl
    - newrelic
    - sodium
# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the environment variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: "mysql:mysql"
  redis: "redis:redis"
  opensearch: "opensearch:opensearch"
  elasticsearch: "elasticsearch:elasticsearch"
  rabbitmq: "rabbitmq:rabbitmq"
# The configuration of app when it is exposed to the web.
web:
  locations:
    "/":
      # The public directory of the app, relative to its root.
      root: "pub"
      # The front-controller script to send non-static requests to.
      passthru: "/index.php"
      index:
        - index.php
      expires: -1
      scripts: true
      allow: false
      rules:
        \.(css|js|map|hbs|gif|jpe?g|png|tiff|wbmp|ico|jng|bmp|svgz|midi?|mp?ga|mp2|mp3|m4a|ra|weba|3gpp?|mp4|mpe?g|mpe|ogv|mov|webm|flv|mng|asx|asf|wmv|avi|ogx|swf|jar|ttf|eot|woff|otf|html?)$:
          allow: true
        /robots\.txt$:
          allow: true
    "/media":
      root: "pub/media"
      allow: true
      scripts: false
      expires: 1y
      passthru: "/get.php"
    "/static":
      root: "pub/static"
      allow: true
      scripts: false
      expires: 1y
      passthru: "/front-static.php"
      rules:
        ^/static/version\d+/(?<resource>.*)$:
          passthru: "/static/$resource"
# The size of the persistent disk of the application (in MB).
disk: 20168
# The mounts that will be performed when the package is deployed.
mounts:
  "var": "shared:files/var"
  "app/etc": "shared:files/etc"
  "pub/media": "shared:files/media"
  "pub/static": "shared:files/static"
# The hooks executed at various points in the lifecycle of the application.
hooks:
  # We run build hooks before your application has been packaged.
  build: |
    set -e
    composer install
    php ./vendor/bin/ece-tools run scenario/build/generate.xml
    php ./vendor/bin/ece-tools run scenario/build/transfer.xml
  # We run deploy hook after your application has been deployed and started.
  deploy: |
    php ./vendor/bin/ece-tools run scenario/deploy.xml
  # We run post deploy hook to clean and warm the cache. Available with ECE-Tools 2002.0.10.
  post_deploy: |
    php ./vendor/bin/ece-tools run scenario/post-deploy.xml

# Default Magento 2 cron jobs
crons:
  cronrun-default:
    spec: "*/1 * * * *"
    cmd: "php bin/magento cron:run --group=default"
  cronrun-index:
    spec: "*/1 * * * *"
    cmd: "php bin/magento cron:run --group=index"
  cronrun-staging:
    spec: "*/1 * * * *"
    cmd: "php bin/magento cron:run --group=staging"
  cronrun-catalog-event:
    spec: "*/1 * * * *"
    cmd: "php bin/magento cron:run --group=catalog_event"
  cronrun-consumers:
    spec: "*/15 * * * *"
    cmd: "php bin/magento cron:run --group=consumers"
  cronrun-feed:
    spec: "*/10 * * * *"
    cmd: "php bin/magento cron:run --group=feed"
  cronrun-folio3_crongroup:
    spec: "*/1 * * * *"
    cmd: "php bin/magento cron:run --group=folio3_crongroup"
  cronrun-rlt_cron_group:
    spec: "*/1 * * * *"
    cmd: "php bin/magento cron:run --group=rlt_cron_group"
  cronrun-rltsquare_abandoned_cart_cron:
    spec: "*/1 * * * *"
    cmd: "php bin/magento cron:run --group=rltsquare_abandoned_cart_cron"
  cronrun-xtento_orderexport:
    spec: "*/15 * * * *"
    cmd: "php bin/magento cron:run --group=xtento_orderexport"
  cronrun-xtento_trackingimport:
    spec: "*/15 * * * *"
    cmd: "php bin/magento cron:run --group=xtento_trackingimport"
  cronrun-webhooks_clean:
    spec: "*/60 * * * *"
    cmd: "php bin/magento cron:run --group=webhooks_clean"

# Environment variables
variables:
  env:
    CONFIG__DEFAULT__PAYPAL_ONBOARDING__MIDDLEMAN_DOMAIN: 'payment-broker.magento.com'
    CONFIG__STORES__DEFAULT__PAYPAL__NOTATION_CODE: 'Magento_Enterprise_Cloud'
