name: Magento Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: phpunit

      - name: Build and package
        run: |
          mkdir -p build
          tar -czf build/app.tar.gz app

      - name: Deploy to AWS
        uses: GullsherChaudhary/mag245@main
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            rm -rf *
            tar -xzf /path/to/build/app.tar.gz

      - name: execute magento commands
        run: |
          php bin/magento setup:upgrade
          php bin/magento setup:di:compile
          php bin/magento setup:static-content:deploy -f
          php bin/magento indexer:reindex
          php bin/magento cache:flush
